# Generated by Django 3.2.9 on 2021-11-29 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.location'),
        ),
    ]
