# Generated by Django 3.2.9 on 2021-11-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20211130_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
